### ISSUE TITLE
Webpack fails during generation

### ISSUE THREAD

**Issue by azdanov** [sebbaum/generator-laravel-5#8]
It happens when `vue` or `react` option is selected. Works well on `none`, `bootstrap`.

```sh
Failed to compile with 1 errors                                                     

This dependency was not found:

* popper.js in ./resources/js/bootstrap.js

To install it, you can run: npm install --save popper.js
     Asset     Size  Chunks                    Chunk Names
/js/app.js  1.61 MB       0  [emitted]  [big]  /js/app

WARNING in ./resources/js/bootstrap.js
Module not found: Error: Can't resolve 'bootstrap' in '/Users/azdanov/Projects/php/laravel/resources/js'
 @ ./resources/js/bootstrap.js 14:2-22
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--8-4!./node_modules/sass-loader/lib/loader.js??ref--8-5!./resources/sass/app.scss
Module build failed:
@import '~bootstrap/scss/bootstrap';
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.
      in /Users/azdanov/Projects/php/laravel/resources/sass/app.scss (line 9, column 1)
 @ ./resources/sass/app.scss 4:14-254
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss
Module build failed: ModuleBuildError: Module build failed:
@import '~bootstrap/scss/bootstrap';
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.
      in /Users/azdanov/Projects/php/laravel/resources/sass/app.scss (line 9, column 1)
    at runLoaders (/Users/azdanov/Projects/php/laravel/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/azdanov/Projects/php/laravel/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/azdanov/Projects/php/laravel/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/azdanov/Projects/php/laravel/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/azdanov/Projects/php/laravel/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/azdanov/Projects/php/laravel/node_modules/neo-async/async.js:7974:18)
    at options.error (/Users/azdanov/Projects/php/laravel/node_modules/node-sass/lib/index.js:294:32)
 @ ./resources/sass/app.scss
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in '/Users/azdanov/Projects/php/laravel/resources/js'
 @ ./resources/js/bootstrap.js 3:16-36
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
```

<details>

<summary>
Full Log
</summary>

```sh
yo laravel-5

Let's create a new Laravel 5 application
? What's the name of your application? laravel
? Which Laravel version do you want to use? 5.7.*
? From where do you serve your application during development? localhost
? Which schema do you want to use? https
? Which laravel frontend preset do you want to use? vue
Installing laravel/laravel (v5.7.0)
  - Installing laravel/laravel (v5.7.0): Loading from cache
Created project in laravel
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 71 installs, 0 updates, 0 removals
  - Installing vlucas/phpdotenv (v2.5.1): Loading from cache
  - Installing symfony/css-selector (v4.1.4): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Loading from cache
  - Installing symfony/polyfill-php72 (v1.9.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.9.0): Loading from cache
  - Installing symfony/var-dumper (v4.1.4): Loading from cache
  - Installing symfony/routing (v4.1.4): Loading from cache
  - Installing symfony/process (v4.1.4): Loading from cache
  - Installing symfony/polyfill-ctype (v1.9.0): Loading from cache
  - Installing symfony/http-foundation (v4.1.4): Loading from cache
  - Installing symfony/event-dispatcher (v4.1.4): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.1.4): Loading from cache
  - Installing symfony/http-kernel (v4.1.4): Loading from cache
  - Installing symfony/finder (v4.1.4): Loading from cache
  - Installing symfony/console (v4.1.4): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing egulias/email-validator (2.1.5): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.1.2): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing ramsey/uuid (3.8.0): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/translation (v4.1.4): Loading from cache
  - Installing nesbot/carbon (1.33.0): Loading from cache
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing league/flysystem (1.0.46): Loading from cache
  - Installing erusev/parsedown (1.7.1): Loading from cache
  - Installing dragonmantank/cron-expression (v2.2.0): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing laravel/framework (v5.7.2): Loading from cache
  - Installing fideloper/proxy (4.0.0): Loading from cache
  - Installing nikic/php-parser (v4.0.3): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing psy/psysh (v0.9.8): Loading from cache
  - Installing laravel/tinker (v1.0.7): Loading from cache
  - Installing beyondcode/laravel-dump-server (1.2.1): Loading from cache
  - Installing fzaninotto/faker (v1.8.0): Loading from cache
  - Installing hamcrest/hamcrest-php (v2.0.0): Loading from cache
  - Installing mockery/mockery (1.1.0): Loading from cache
  - Installing filp/whoops (2.2.1): Loading from cache
  - Installing nunomaduro/collision (v2.0.3): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (3.0.1): Loading from cache
  - Installing sebastian/comparator (3.0.2): Loading from cache
  - Installing phpunit/php-timer (2.0.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-file-iterator (2.0.1): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (3.0.0): Loading from cache
  - Installing phpunit/php-code-coverage (6.0.7): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.8.0): Loading from cache
  - Installing phar-io/version (2.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.3): Loading from cache
  - Installing myclabs/deep-copy (1.8.1): Loading from cache
  - Installing phpunit/phpunit (7.3.5): Loading from cache
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/http-kernel suggests installing symfony/browser-kit
symfony/http-kernel suggests installing symfony/config
symfony/http-kernel suggests installing symfony/dependency-injection
symfony/console suggests installing symfony/lock
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (^3.0).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (^2.6).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (^6.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (^1.0).)
laravel/framework suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (^1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (^1.0).)
laravel/framework suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (^1.0).)
laravel/framework suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (^1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (^3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (^1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (^3.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (^4.1).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (^1.0).)
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
> @php artisan key:generate
Application key [base64:2ON1hnZxCd3PB11m9Kioit4Qqwzj0SyfGlHoZBeB6yY=] set successfully.
Using version ^2.8 for doctrine/dbal
Using version ^2.5 for barryvdh/laravel-ide-helper
Using version ^3.2 for barryvdh/laravel-debugbar
Using version ^0.11.2 for barryvdh/laravel-cors
Using version ^2.4 for phpmetrics/phpmetrics
Using version ^1.0 for beyondcode/laravel-self-diagnosis
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing geerlingguy/ping (1.1.2): Loading from cache
  - Installing composer/semver (1.4.2): Loading from cache
  - Installing beyondcode/laravel-self-diagnosis (1.0.2): Loading from cache
  - Installing asm89/stack-cors (1.2.0): Loading from cache
  - Installing barryvdh/laravel-cors (v0.11.2): Loading from cache
  - Installing maximebf/debugbar (v1.15.0): Loading from cache
  - Installing barryvdh/laravel-debugbar (v3.2.0): Loading from cache
  - Installing symfony/filesystem (v4.1.4): Loading from cache
  - Installing seld/phar-utils (1.0.1): Loading from cache
  - Installing seld/jsonlint (1.7.1): Loading from cache
  - Installing justinrainbow/json-schema (5.2.7): Loading from cache
  - Installing composer/xdebug-handler (1.3.0): Loading from cache
  - Installing composer/spdx-licenses (1.4.0): Loading from cache
  - Installing composer/ca-bundle (1.1.2): Loading from cache
  - Installing composer/composer (1.7.2): Loading from cache
  - Installing barryvdh/reflection-docblock (v2.0.4): Loading from cache
  - Installing barryvdh/laravel-ide-helper (v2.5.1): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/cache (v1.8.0): Loading from cache
  - Installing doctrine/dbal (v2.8.0): Loading from cache
  - Installing phpmetrics/phpmetrics (v2.4.1): Loading from cache
maximebf/debugbar suggests installing kriswallsmith/assetic (The best way to manage assets)
maximebf/debugbar suggests installing predis/predis (Redis storage)
barryvdh/reflection-docblock suggests installing dflydev/markdown (~1.0)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-cors
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: beyondcode/laravel-self-diagnosis
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-cors": "^0.11.2",
        "barryvdh/laravel-debugbar": "^3.2",
        "barryvdh/laravel-ide-helper": "^2.5",
        "beyondcode/laravel-dump-server": "^1.0",
        "beyondcode/laravel-self-diagnosis": "^1.0",
        "doctrine/dbal": "^2.8",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpmetrics/phpmetrics": "^2.4",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

   create composer.json
   create webpack.mix.js
   create package.json
   create .gitignore
Vue scaffolding installed successfully.
Please run "npm install && npm run dev" to compile your fresh scaffolding.


I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.



> fsevents@1.2.4 install /Users/azdanov/Projects/php/laravel/node_modules/fsevents
> node install

[fsevents] Success: "/Users/azdanov/Projects/php/laravel/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN browser-sync-webpack-plugin@2.2.2 requires a peer of webpack@^1 || ^2 || ^3 || ^4 but none is installed. You must install peer dependencies yourself.

+ browser-sync-webpack-plugin@2.2.2
+ browser-sync@2.24.7
added 291 packages from 207 contributors and audited 640 packages in 6.534s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> node-sass@4.9.3 install /Users/azdanov/Projects/php/laravel/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/azdanov/.npm/node-sass/4.9.3/darwin-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/azdanov/Projects/php/laravel/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.3 postinstall /Users/azdanov/Projects/php/laravel/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/azdanov/Projects/php/laravel/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall /Users/azdanov/Projects/php/laravel/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> mozjpeg@5.0.0 postinstall /Users/azdanov/Projects/php/laravel/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /Users/azdanov/Projects/php/laravel/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@4.0.0 postinstall /Users/azdanov/Projects/php/laravel/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

added 1280 packages from 708 contributors and audited 18559 packages in 37.347s
found 8 vulnerabilities (1 low, 7 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

> @ dev /Users/azdanov/Projects/php/laravel
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting

 ERROR  Failed to compile with 1 errors                                                     04:33:07

This dependency was not found:

* popper.js in ./resources/js/bootstrap.js

To install it, you can run: npm install --save popper.js
     Asset     Size  Chunks                    Chunk Names
/js/app.js  1.17 MB       0  [emitted]  [big]  /js/app

WARNING in ./resources/js/bootstrap.js
Module not found: Error: Can't resolve 'bootstrap' in '/Users/azdanov/Projects/php/laravel/resources/js'
 @ ./resources/js/bootstrap.js 14:2-22
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/lib??postcss!./node_modules/resolve-url-loader??ref--8-4!./node_modules/sass-loader/lib/loader.js??ref--8-5!./resources/sass/app.scss
Module build failed:
@import '~bootstrap/scss/bootstrap';
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.
      in /Users/azdanov/Projects/php/laravel/resources/sass/app.scss (line 9, column 1)
 @ ./resources/sass/app.scss 4:14-254
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss
Module build failed: ModuleBuildError: Module build failed:
@import '~bootstrap/scss/bootstrap';
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.
      in /Users/azdanov/Projects/php/laravel/resources/sass/app.scss (line 9, column 1)
    at runLoaders (/Users/azdanov/Projects/php/laravel/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/azdanov/Projects/php/laravel/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/azdanov/Projects/php/laravel/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/azdanov/Projects/php/laravel/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/azdanov/Projects/php/laravel/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/azdanov/Projects/php/laravel/node_modules/neo-async/async.js:7974:18)
    at options.error (/Users/azdanov/Projects/php/laravel/node_modules/node-sass/lib/index.js:294:32)
 @ ./resources/sass/app.scss
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in '/Users/azdanov/Projects/php/laravel/resources/js'
 @ ./resources/js/bootstrap.js 3:16-36
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/azdanov/.npm/_logs/2018-09-11T01_33_07_460Z-debug.log
The [public/storage] directory has been linked.
|-------------------------------------
| Common Checks
|-------------------------------------
Running check 1/11: App key is set...  ✔
Running check 2/11: The correct PHP version is installed...  ✔
Running check 3/11: The database can be accessed...  ✘
Running check 4/11: All directories have the correct permissions...  ✔
Running check 5/11: The environment file exists...  ✔
Running check 6/11: The example environment variables are set...  ✔
Running check 7/11: Required locales are installed...  ✘
Running check 8/11: Maintenance mode is not enabled...  ✔
Running check 9/11: The migrations are up to date...  ✘
Running check 10/11: The required PHP extensions are installed...  ✔
Running check 11/11: The storage directory is linked...  ✔

|-------------------------------------
| Environment Specific Checks (local)
|-------------------------------------
Running check 1/4: Composer dependencies (including dev) are up to date...  ✔
Running check 2/4: Configuration is not cached...  ✔
Running check 3/4: Routes are not cached...  ✔
Running check 4/4: The example environment variables are up-to-date...  ✔

The following checks failed:
The database can not be accessed: SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)

The following locales are missing:
en_US.utf8

Unable to check for migrations: SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations)
```

<details>

**Comment by sebbaum** [comment]
Thanks again for pointing me at this bug. I'll address the issue as soon as possible.

Cheers
Sebastian

**Comment by sebbaum** [comment]
I am currently testing all the variations of presets and their required dependencies. I am also writing automated tests to assert, that everything is set up properly. This will still take some time.

Meanwhile, you can fix this bug by installing the required dependencies manually:
`npm i popper.js bootstrap --save-dev`
`npm i vue popper.js bootstrap --save-dev`
etc.
The error output will tell you what's missing.

Cheers
Sebastian
